version: '3'

services:
  database:
    container_name: pg_container
    image: postgres:12.3-alpine
    environment:
      POSTGRES_DB: guitartracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgres/data
    volumes:
      - database-data:/var/lib/postgresql/data #persist data even if container shuts down
    ports:
        - "5444:5432"
 

volumes:
  database-data: #